platform :ios, '13.4'
require_relative '../node_modules/react-native/scripts/react_native_pods'

prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'PoliciaTorreonApp' do
  config = use_native_modules!
   
  pod 'Firebase', :modular_headers => true
  pod 'Firebase/Core', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => false
  )
  
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  post_install do |installer|
    react_native_post_install(installer)
  end
end
